---
title: "O-download"
output:
  pdf_document: default
  html_notebook: default
---

```{r, message = FALSE}
library(kableExtra)                     # for printing tables
library(tidyverse)                      # for everything else
```

```{r}
vh_data_raw = 
  read_csv("../data/raw/pulse2021_puf_39.csv")
    # # specify column types
    # col_types = list(
    #   TBIRTH_YEAR = col_integer(), 
    #   RHISPANIC = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   RRACE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   EEDUC = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MS = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   EGENID_BIRTH = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   GENID_DESCRIBE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SEXUAL_ORIENTATION = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   THHLD_NUMPER = col_integer(), 
    #   THHLD_NUMKID = col_integer(),
    #   THHLD_NUMADLT = col_integer(),
    #   KIDS_LT5Y = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   KIDS_5_11Y = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   KIDS_12_17Y = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TENROLLPUB = col_integer(),
    #   TENROLLPRV = col_integer(),
    #   TENROLLHMSCH = col_integer(),
    #   ENROLLNONE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTVDUTY1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTVDUTY2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTVDUTY3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTVDUTY4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTVDUTY5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   RECVDVACC = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   DOSESRV = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE), 
    #   GETVACRV = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   KIDDOSES = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   KIDGETVAC = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HADCOVID = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   WRKLOSSRV = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ANYWORK = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   KINDWORK = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   RSNNOWRKRV = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   WKVOL = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SETTING = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDCARE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT8 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHLDIMPCT9 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTC_YN = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTC_USE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND8 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND9 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND10 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND11 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND12 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND13 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND14 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND15 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND16 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CTCSPND17 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   EXPNS_DIF = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ACTIVITY6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC8 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC9 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC10 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC11 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SPND_SRC12 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CURFOODSUF = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   CHILDFOOD = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FOODRSNRV1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FOODRSNRV2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FOODRSNRV3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FOODRSNRV4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FREEFOOD = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SCHLFDHLP1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SCHLFDHLP2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SCHLFDHLP3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SCHLFDHLP4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   NOSCHLFDHLP = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SNAP_YN = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ANXIOUS = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   WORRY = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   DOWN = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE), 
    #   INTEREST = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PRESCRIPT = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MH_SVCS = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MH_NOTGET = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HLTHINS8 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TELEHLTH = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TH_ADLT_PHON = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TH_ADLT_VID = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TELECHLD = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TH_CHLD_PHON = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PRVNTIVE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SEEING = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HEARING = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   REMEMBERING = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MOBILITY = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TENURE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   LIVQTRRV = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   RENTCUR = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MORTCUR = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   MORTCONF = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TMNTHSBHND = col_integer(),
    #   RENTASSIST = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   EVICT = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   FORCLOSE = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ENERGY = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   HSE_TEMP = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   ENRGY_BILL = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SUMMER_ED1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SUMMER_ED2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SUMMER_ED3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   SUMMER_ED4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   TNUM_PS = col_integer(),
    #   PSCHNG1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSCHNG7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG1 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG2 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG3 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG4 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG5 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG6 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG7 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG8 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PSWHYCHG9 = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   INCOME = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   EST_ST = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PWEIGHT = col_double(),
    #   HWEIGHT = col_double(),
    #   PRIVHLTH = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   PUBHLTH = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE),
    #   REGION = col_factor(levels = NULL, ordered = FALSE, include_na = FALSE)))

# write raw data to file 
write_tsv(x = vh_data_raw, file = "../data/raw/vh_data_raw.tsv")
```
